### ISSUE TITLE
.tmp building method is unclear for SASS

### ISSUE THREAD

**Issue by develra** [sikuli/viz#7]
Heya,

Mike and I were messing around with the scss - trying to get the header to render in a more reasonable way. - .tmp builds on the initial pass, but then if it exists and we delete a scss file, the main.css in temp appears to still maintain those (now deleted) styles. We were looking at the gulp SCSS builder, and couldn't quite figure out what it is specifically doing. Could you take a look at this?

Thanks

**Comment by develra** [comment]
This issue can actually be simplified to "Gulp doesn't currently support SASS"

**Comment by ianks** [comment]
This will be fixed once https://github.com/sikuli/viz/commit/b9ca16c00999d6d601c68ae87b2ea9d39aaa5d0c is merged.
